import Foundation
import CrowCore

/// Installs the Crow ↔ OpenCode state bridge. OpenCode has **no**
/// command-based hook file like Claude Code's `settings.json` or Cursor's
/// `hooks.json`; instead it auto-loads JS/TS **plugins** from
/// `~/.config/opencode/plugins/` (global) and `<project>/.opencode/plugins/`
/// (per-project). MVP is global-only, matching Codex/Cursor's scope.
///
/// So `installGlobalConfig` writes a single plugin file,
/// `crow-hooks.js`, that subscribes to OpenCode's `event` bus plus the
/// `tool.execute.before/after` hooks and shells out (via Bun's `$`) to
/// `crow hook-event --agent opencode --event <PascalName>`, piping a JSON
/// payload with the worktree `cwd` on stdin — exactly the shape the crow
/// server's `hook-event` RPC expects (it resolves the session by matching
/// `cwd` against registered worktree paths, the same mechanism Codex's
/// global hooks use).
///
/// The plugin maps OpenCode's event vocabulary onto Crow's canonical
/// PascalCase names so `OpenCodeSignalSource` can share Claude/Codex/Cursor's
/// vocabulary verbatim:
///
///   session.created       → SessionStart
///   tool.execute.before   → PreToolUse
///   tool.execute.after    → PostToolUse
///   session.idle          → Stop          (the canonical "agent finished")
///   permission.asked      → PermissionRequest
///   session.error         → Notification
///
/// CROW-545 gap: the exact OpenCode event → state timing (esp. whether
/// `session.idle` is the right "done" signal for headless `opencode run`)
/// should be confirmed empirically at runtime, the same caveat Cursor's
/// writer carries for `afterAgentResponse`.
///
/// Because `HookConfigWriter`'s per-session API doesn't fit OpenCode's
/// global model, the per-session methods are intentionally no-ops — real
/// work happens via the static `installGlobalConfig` call at app launch.
public struct OpenCodeHookConfigWriter: HookConfigWriter {

    public init() {}

    // MARK: - HookConfigWriter Conformance (no-ops)

    /// No-op. OpenCode plugins are global, not per-worktree — see
    /// `installGlobalConfig`. Per-project `<worktree>/.opencode/plugins/` is
    /// deferred to a follow-up; MVP stays global-only.
    public func writeHookConfig(worktreePath: String, sessionID: UUID, crowPath: String) throws {}

    /// No-op. The global plugin stays in place when individual sessions are
    /// deleted; it serves all sessions.
    public func removeHookConfig(worktreePath: String) {}

    // MARK: - Global Configuration

    /// Install or refresh `<configHome>/plugins/crow-hooks.js`. `configHome`
    /// is OpenCode's config dir (default `~/.config/opencode`, honoring
    /// `XDG_CONFIG_HOME`). Idempotent — we own this single-purpose file and
    /// overwrite it wholesale on every launch, so there's nothing to merge
    /// (unlike Cursor's shared `hooks.json`).
    public static func installGlobalConfig(configHome: String, crowPath: String) throws {
        let pluginsDir = (configHome as NSString).appendingPathComponent("plugins")
        try FileManager.default.createDirectory(atPath: pluginsDir, withIntermediateDirectories: true)
        let pluginPath = (pluginsDir as NSString).appendingPathComponent("crow-hooks.js")
        let content = pluginSource(crowPath: crowPath)
        try content.write(to: URL(fileURLWithPath: pluginPath), atomically: true, encoding: .utf8)
    }

    /// The JS plugin body, with `crowPath` baked in as a string literal
    /// (mirrors how Cursor bakes `crowPath` into its `hooks.json` commands).
    /// Written as plain `.js` so it needs no `@opencode-ai/plugin` types or
    /// a build step — OpenCode runs it directly on Bun.
    static func pluginSource(crowPath: String) -> String {
        let crow = jsStringLiteral(crowPath)
        return """
        // Crow ↔ OpenCode hook bridge — auto-generated by Crow (safe to delete).
        // Forwards OpenCode lifecycle events to the running Crow app so session
        // cards reflect agent state. Regenerated on every Crow launch.
        //
        // Each emit pipes a JSON payload ({ cwd, ... }) to `crow hook-event`;
        // the crow server resolves the Crow session by matching `cwd` against
        // registered worktree paths, so no session UUID is needed here.
        const CROW = \(crow);

        async function emit($, cwd, event, extra) {
          try {
            const payload = JSON.stringify(Object.assign({ cwd }, extra || {}));
            await $`echo ${payload} | ${CROW} hook-event --agent opencode --event ${event}`.quiet();
          } catch (_) {
            // Fire-and-forget: a hook failure (e.g. Crow not running) must
            // never disrupt OpenCode.
          }
        }

        export const CrowHooks = async ({ directory, worktree, $ }) => {
          // Prefer the git worktree path — that's what Crow registers and
          // matches on. Fall back to the process cwd.
          const cwd = worktree || directory;
          return {
            event: async ({ event }) => {
              switch (event.type) {
                case "session.created":
                  await emit($, cwd, "SessionStart", { source: "startup" });
                  break;
                case "session.idle":
                  // OpenCode has finished the turn and is waiting on the user.
                  await emit($, cwd, "Stop");
                  break;
                case "permission.asked":
                  await emit($, cwd, "PermissionRequest");
                  break;
                case "session.error":
                  await emit($, cwd, "Notification", { message: "Session error" });
                  break;
              }
            },
            "tool.execute.before": async (input) => {
              await emit($, cwd, "PreToolUse", { tool_name: (input && input.tool) || "unknown" });
            },
            "tool.execute.after": async (input) => {
              await emit($, cwd, "PostToolUse", { tool_name: (input && input.tool) || "unknown" });
            },
          };
        };

        """
    }

    /// Escape a path for embedding inside a JS double-quoted string literal.
    /// Paths won't normally contain quotes/backslashes, but escape defensively.
    private static func jsStringLiteral(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
