import Foundation

/// A Claude Code hook event received from a session's Claude Code instance.
///
/// Hook events are generated by Claude Code's hook system and forwarded to Crow
/// via the `crow hook-event` CLI command. Each event captures the event type,
/// a human-readable summary, and the originating session.
public struct HookEvent: Identifiable, Sendable {
    /// Unique identifier for this event instance.
    public let id: UUID
    /// The session that generated this event.
    public let sessionID: UUID
    /// The raw hook event name (e.g. "Stop", "PreToolUse", "PermissionRequest").
    public let eventName: String
    /// Human-readable summary of the event for display in notifications.
    public let summary: String
    /// When the event was received.
    public let timestamp: Date

    public init(
        id: UUID = UUID(),
        sessionID: UUID,
        eventName: String,
        summary: String,
        timestamp: Date = Date()
    ) {
        self.id = id
        self.sessionID = sessionID
        self.eventName = eventName
        self.summary = summary
        self.timestamp = timestamp
    }
}
