#!/usr/bin/env bash
# Generate BuildInfo.swift with git SHA and build date
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$ROOT_DIR/Sources/Crow/Generated"
OUTPUT_FILE="$OUTPUT_DIR/BuildInfo.swift"

mkdir -p "$OUTPUT_DIR"

# Capture git info (fallback to "dev" if not in a git repo)
if git -C "$ROOT_DIR" rev-parse HEAD >/dev/null 2>&1; then
    GIT_SHA=$(git -C "$ROOT_DIR" rev-parse HEAD)
    GIT_SHORT_SHA=$(git -C "$ROOT_DIR" rev-parse --short HEAD)
else
    GIT_SHA="dev"
    GIT_SHORT_SHA="dev"
fi

BUILD_DATE=$(date -u +"%Y-%m-%d")

cat > "$OUTPUT_FILE" << EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit
enum BuildInfo {
    static let gitCommitSHA = "$GIT_SHA"
    static let gitCommitShortSHA = "$GIT_SHORT_SHA"
    static let buildDate = "$BUILD_DATE"
}
EOF

echo "Generated $OUTPUT_FILE (SHA: $GIT_SHORT_SHA, date: $BUILD_DATE)"
