#!/usr/bin/env bash
# Generate BuildInfo.swift and CLIVersion.swift with git SHA, build date, and version
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# --- Version ---
if [ -n "${VERSION:-}" ]; then
    APP_VERSION="$VERSION"
elif [ -f "$ROOT_DIR/VERSION" ]; then
    APP_VERSION="$(tr -d '[:space:]' < "$ROOT_DIR/VERSION")"
else
    APP_VERSION="0.1.0"
fi

# --- Git info ---
if git -C "$ROOT_DIR" rev-parse HEAD >/dev/null 2>&1; then
    GIT_SHA=$(git -C "$ROOT_DIR" rev-parse HEAD)
    GIT_SHORT_SHA=$(git -C "$ROOT_DIR" rev-parse --short HEAD)
else
    GIT_SHA="dev"
    GIT_SHORT_SHA="dev"
fi

BUILD_DATE=$(date -u +"%Y-%m-%d")

# --- Generate BuildInfo.swift (Crow app target) ---
OUTPUT_DIR="$ROOT_DIR/Sources/Crow/Generated"
OUTPUT_FILE="$OUTPUT_DIR/BuildInfo.swift"
mkdir -p "$OUTPUT_DIR"

cat > "$OUTPUT_FILE" << EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit
enum BuildInfo {
    static let version = "$APP_VERSION"
    static let gitCommitSHA = "$GIT_SHA"
    static let gitCommitShortSHA = "$GIT_SHORT_SHA"
    static let buildDate = "$BUILD_DATE"
}
EOF

echo "Generated $OUTPUT_FILE (version: $APP_VERSION, SHA: $GIT_SHORT_SHA, date: $BUILD_DATE)"

# --- Generate CLIVersion.swift (CrowCLI target) ---
CLI_OUTPUT_DIR="$ROOT_DIR/Sources/CrowCLI/Generated"
CLI_OUTPUT_FILE="$CLI_OUTPUT_DIR/CLIVersion.swift"
mkdir -p "$CLI_OUTPUT_DIR"

cat > "$CLI_OUTPUT_FILE" << EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit
enum CLIVersion {
    static let version = "$APP_VERSION"
}
EOF

echo "Generated $CLI_OUTPUT_FILE"
