#!/usr/bin/env bash
# Generate BuildInfo.swift and CLIVersion.swift with version, git SHA, and build date.
#
# Output: Sources/Crow/Generated/BuildInfo.swift
#         Sources/CrowCLI/Generated/CLIVersion.swift
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
APP_OUTPUT_DIR="$ROOT_DIR/Sources/Crow/Generated"
CLI_OUTPUT_DIR="$ROOT_DIR/Sources/CrowCLI/Generated"

mkdir -p "$APP_OUTPUT_DIR" "$CLI_OUTPUT_DIR"

# Read version: CROW_VERSION env var takes precedence, then VERSION file
if [ -n "${CROW_VERSION:-}" ]; then
    VERSION="$CROW_VERSION"
elif [ -f "$ROOT_DIR/VERSION" ]; then
    VERSION="$(tr -d '[:space:]' < "$ROOT_DIR/VERSION")"
else
    echo "ERROR: No VERSION file found and CROW_VERSION not set" >&2
    exit 1
fi

# Capture git info (fallback to "dev" if not in a git repo)
if git -C "$ROOT_DIR" rev-parse HEAD >/dev/null 2>&1; then
    GIT_SHA=$(git -C "$ROOT_DIR" rev-parse HEAD)
    GIT_SHORT_SHA=$(git -C "$ROOT_DIR" rev-parse --short HEAD)
    BUILD_NUMBER=$(git -C "$ROOT_DIR" rev-list --count HEAD)
else
    GIT_SHA="dev"
    GIT_SHORT_SHA="dev"
    BUILD_NUMBER="1"
fi

BUILD_DATE=$(date -u +"%Y-%m-%d")

# Generate BuildInfo.swift for the GUI app
cat > "$APP_OUTPUT_DIR/BuildInfo.swift" << EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit
enum BuildInfo {
    static let version = "$VERSION"
    static let buildNumber = "$BUILD_NUMBER"
    static let gitCommitSHA = "$GIT_SHA"
    static let gitCommitShortSHA = "$GIT_SHORT_SHA"
    static let buildDate = "$BUILD_DATE"
}
EOF

# Generate CLIVersion.swift for the CLI tool
cat > "$CLI_OUTPUT_DIR/CLIVersion.swift" << EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit
enum CLIVersion {
    static let version = "$VERSION"
}
EOF

echo "Generated build info (version: $VERSION, build: $BUILD_NUMBER, SHA: $GIT_SHORT_SHA, date: $BUILD_DATE)"
